version: "3.9"
services:
  facade:
    build: ./facade_service
    ports:
      - "${PORT}:8080"
  logging:
    build: ./logging_service
    scale: 3
  messages:
    build: ./messages_service
  # hazelcast:
  #   image: hazelcast/hazelcast:5.0
