app:
  port: 5002
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 30
  redis_ttl: 100800

redis:
  host: localhost
  port: 6379
  db: 0
  prefix: choice

database:
  host: localhost
  port: 3306
  name: choice
  username: root
  password: 12345
